# Generated by Django 5.2.15 on 2026-07-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_sync_admin_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('plan_confirmado', 'Plan confirmado'), ('plan_rechazado', 'Plan rechazado'), ('precio_plan_actualizado', 'Precio de plan actualizado'), ('clase_agendada', 'Clase agendada'), ('clase_bloqueada', 'Clase bloqueada'), ('clase_desbloqueada', 'Clase desbloqueada'), ('horas_profesora_ajustadas', 'Horas de profesora ajustadas'), ('clases_extra_agregadas', 'Clases extra agregadas')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registro_admin_acciones',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asistencias_clases',
                'ordering': ('class_session__starts_at', 'user__nombre', 'user__apellido'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassCreditAdjustment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ajustes_clases',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField(blank=True, null=True)),
                ('confirmation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservas_clases',
                'ordering': ('class_session__starts_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(unique=True)),
                ('ends_at', models.DateTimeField()),
                ('capacidad_maxima', models.PositiveIntegerField(default=4)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agenda_clases',
                'ordering': ('starts_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'landing_leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanCatalog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=10)),
                ('clases_por_mes', models.PositiveIntegerField()),
                ('frecuencia', models.CharField(max_length=60)),
                ('precio_mensual', models.PositiveIntegerField()),
                ('precio_trimestral', models.PositiveIntegerField()),
                ('precio_semestral', models.PositiveIntegerField()),
                ('es_clase_suelta', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planes_catalogo',
                'ordering': ('orden', 'id'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semester', 'Semestral')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('presencial', 'Pago en estudio'), ('transferencia', 'Transferencia')], default='presencial', max_length=20)),
                ('detalle_transferencia', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('comprobante_path', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revision'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solicitudes_planes',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SingleClassBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('metodo_pago', models.CharField(choices=[('presencial', 'Pago en estudio'), ('transferencia', 'Transferencia')], default='presencial', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('comprobante_path', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solicitudes_clase_suelta',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherHoursAdjustment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('minutes_delta', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ajustes_horas_profesoras',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherMonthlyShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('shift_kind', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('sabado', 'Sabado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'turnos_profesoras_mensual',
                'ordering': ('year', 'month', 'shift_kind'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSessionNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notas_profesoras_clases',
                'ordering': ('-updated_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_date', models.DateField()),
                ('shift_kind', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('sabado', 'Sabado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'turnos_profesoras',
                'ordering': ('shift_date', 'shift_kind'),
                'managed': False,
            },
        ),
    ]
